<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="FEM\Core\Assembling\Local\CylindricalLocalMatricesAssembler.cs~RFee5fed.TMP" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="FEM\2D\Grid\" />
    <Folder Include="FEM\Assembling\Global\" />
    <Folder Include="FEM\Assembling\Providers\" />
    <Folder Include="FEM\Core\Assembling\Global\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.Linq.Dynamic.Core" Version="1.6.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DirectProblem\DirectProblem.csproj" />
    <ProjectReference Include="..\Domain\Domain.csproj" />
  </ItemGroup>

</Project>
