<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Program.cs~RF55432.TMP" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Services\Application.csproj" />
    <ProjectReference Include="..\Tests\Tests.csproj" />
  </ItemGroup>

</Project>
